# docker-compose.yml

version: "3.2"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  user_management:
    build: ./42-matcha-backend/user-management
    depends_on:
      - flyway
    environment:
      DB_URL: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      # DB_PASSWORD: /run/secrets/postgres_passwd
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      PORT: ${USER_MANAGEMENT_PORT}
    secrets:
      - postgres_passwd
    ports:
      - 8001:${USER_MANAGEMENT_PORT}
      - 9229:9229
    networks:
      - db
      - nginx

  flyway:
    image: flyway/flyway
    # command: -url=jdbc:postgresql://db/${DB_NAME} -schemas=matcha -user=portfolio -password=psswd migrate
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      FLYWAY_USER: ${DB_USER}
      # FLYWAY_PASSWORD: /run/secrets/postgres_passwd
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 60
    secrets:
      - postgres_passwd
    depends_on:
      - db
    volumes:
      - ./migrations:/flyway/sql
    networks:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      PGUSER: ${DB_USER}
      # POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
      # PGPASSWORD: /run/secrets/postgres_passwd
      POSTGRES_PASSWORD_FILE: ${DB_PASSWORD}
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATABASE: ${DB_NAME}
      PGPORT: ${DB_PORT}
    volumes:
      - matcha_db:/var/lib/postgresql/data
    networks:
      - db
    secrets:
      - postgres_passwd
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

volumes:
  matcha_db:

secrets:
  postgres_passwd:
    file: ./pwd

networks:
  db:
  nginx:
